version: "3.9"

services:
  postgres:
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-password}
      POSTGRES_DB: ${POSTGRES_DB:-db}
    ports:
      - "5432:5432"
    volumes:
      - "/data/db:/var/lib/postgresql/data:z"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      "server start"
    env_file:
      - '.env'
    depends_on:
      - postgres 
    ports:
      - "8080:8080"

